// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TarotDestiny.Api.Data;

#nullable disable

namespace TarotDestiny.Api.Data.Migrations
{
    [DbContext(typeof(TarotDbContext))]
    [Migration("20260830155409_ClassifierDatasetV2Review")]
    partial class ClassifierDatasetV2Review
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TarotDestiny.Api.Data.ClassifierTrainingExampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassifierModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("classifier_model_version");

                    b.Property<string>("ClassifierSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classifier_source");

                    b.Property<string>("ConsentVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale");

                    b.Property<string>("ParaphraseGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paraphrase_group");

                    b.Property<double>("PredictedConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("predicted_confidence");

                    b.Property<string>("PredictedDomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("predicted_domain");

                    b.Property<string>("PredictedIntent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("predicted_intent");

                    b.Property<string>("PredictedPersonalization")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("predicted_personalization");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.Property<string>("QuestionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("question_hash");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("review_status");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedDomain")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reviewed_domain");

                    b.Property<string>("ReviewedIntent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewed_intent");

                    b.Property<string>("ReviewedPersonalization")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reviewed_personalization");

                    b.Property<int?>("ReviewerTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("reviewer_time_seconds");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_tarot_question_classification_training");

                    b.HasIndex("QuestionHash")
                        .IsUnique()
                        .HasDatabaseName("ux_tarot_training_question_hash");

                    b.HasIndex("ReviewStatus", "CreatedAt")
                        .HasDatabaseName("ix_tarot_training_review_status_created_at");

                    b.ToTable("tarot_question_classification_training", null, t =>
                        {
                            t.HasCheckConstraint("ck_tarot_training_confidence", "predicted_confidence >= 0 AND predicted_confidence <= 1");

                            t.HasCheckConstraint("ck_tarot_training_question_hash", "length(question_hash) = 64");

                            t.HasCheckConstraint("ck_tarot_training_review_status", "review_status IN ('PENDING', 'APPROVED', 'REJECTED')");

                            t.HasCheckConstraint("ck_tarot_training_reviewed_personalization", "reviewed_personalization IS NULL OR reviewed_personalization IN ('LOW', 'MEDIUM', 'HIGH')");

                            t.HasCheckConstraint("ck_tarot_training_reviewer_time", "reviewer_time_seconds IS NULL OR reviewer_time_seconds >= 0");

                            t.HasCheckConstraint("ck_tarot_training_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("TarotDestiny.Api.Data.GeneratedAnswerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CacheHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cache_hash");

                    b.Property<string>("CacheVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cache_version");

                    b.Property<string>("CardsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cards");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("domain");

                    b.Property<long>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("hit_count");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("intent");

                    b.Property<string>("InterpretationVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("interpretation_version");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ReadingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reading_mode");

                    b.Property<string>("SpreadId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("spread_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tarot_generated_answer");

                    b.HasIndex("CacheHash")
                        .IsUnique()
                        .HasDatabaseName("ux_tarot_generated_answer_cache_hash");

                    b.HasIndex("HitCount")
                        .IsDescending()
                        .HasDatabaseName("ix_tarot_generated_answer_hit_count");

                    b.HasIndex("Domain", "Intent", "ReadingMode")
                        .HasDatabaseName("ix_tarot_generated_answer_domain_intent_reading_mode");

                    b.ToTable("tarot_generated_answer", null, t =>
                        {
                            t.HasCheckConstraint("ck_tarot_generated_answer_cache_hash", "length(cache_hash) = 64");

                            t.HasCheckConstraint("ck_tarot_generated_answer_hit_count", "hit_count >= 0");
                        });
                });

            modelBuilder.Entity("TarotDestiny.Api.Data.GeneratedAnswerVariantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GeneratedAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_answer_id");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<int>("VariantNumber")
                        .HasColumnType("integer")
                        .HasColumnName("variant_number");

                    b.HasKey("Id")
                        .HasName("pk_tarot_generated_answer_variant");

                    b.HasIndex("GeneratedAnswerId", "VariantNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_tarot_generated_answer_variant_answer_number");

                    b.ToTable("tarot_generated_answer_variant", null, t =>
                        {
                            t.HasCheckConstraint("ck_tarot_generated_answer_variant_number", "variant_number > 0");
                        });
                });

            modelBuilder.Entity("TarotDestiny.Api.Data.GeneratedAnswerVariantEntity", b =>
                {
                    b.HasOne("TarotDestiny.Api.Data.GeneratedAnswerEntity", "GeneratedAnswer")
                        .WithMany("Variants")
                        .HasForeignKey("GeneratedAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tarot_generated_answer_variant_answer");

                    b.Navigation("GeneratedAnswer");
                });

            modelBuilder.Entity("TarotDestiny.Api.Data.GeneratedAnswerEntity", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
